### ISSUE TITLE
Asciidoctor rendering ignores image attributes

### ISSUE THREAD

**Issue by jtama** [yupiik/tools-maven-plugin#24]
**Describe the bug**
The only attribute honored is the "alt" attribute, and it may even be erroneous, as the no name attribute is the first to be looked up.
I think at least the following attributes should be honored : 

- Width
- Height
- roles

**To Reproduce**
```
image::whatever.png[Acme 300 200]
// Also
image::whatever.png[alt="Acme", 300 200]
```

**Actual behavior**
```
<img src="whatever.png" alt="Acme 300 200">
```

**Expected behavior**
`<img src="whatever.png" alt="Acme" width=300 height=200">`

**Additional context**
Unlabelled attributes should also be ignored if the `alt` attribute is provided.

**Comment by fpapon** [comment]
@jtama make sense, do you plan to provide a PR?

**Comment by jtama** [comment]
I can do that.

**Comment by jtama** [comment]
Done

**Comment by fpapon** [comment]
@jtama merged, thanks for your contribution!

**Comment by fpapon** [comment]
@jtama 1.2.5 has been released and is available on central.

**Comment by jtama** [comment]
This should be update in quarkus-web-asciidoc on next dependabot run
